module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: { '^.+\\.(t|j)s$': 'ts-jest' },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!main.ts',
    '!**/*.module.ts',
    '!**/*.repository.ts',
    '!**/*.entity.ts',
    '!**/*.interface.ts',
    '!database/data-source.ts',
    '!database/migrations/**',
    '!database/seeds/**',
    '!config/**',
    '!auth/strategies/**',
    '!common/guards/**',
    '!common/interceptors/**',
    '!common/filters/**',
    '!common/decorators/**',
    '!common/dto/**',
    '!common/events/**',
    '!**/*.dto.ts',
    '!**/listeners/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coverageThreshold: {
    global: { branches: 80, functions: 80, lines: 80, statements: 80 },
  },
};
